name: Checkout and Build
on: [push]

jobs:
  checkout-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: List Files Before
        run: ls -a
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
         node-version: ${{ matrix.node-version }}
      - name: List Files After
        run: ls -a
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: ls -a
      - name: Checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: Build
        run: |
          ls -a
          cd src
          npm ci
          npm run build --if-present
          npm test
      - name: List Files
        run: |
          ls -a
          echo "File listed"
          pwd
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
         name: dist
         path: README.md


        
